version: '3.9'

services:
  legacy-cloud-acl:
    image: grozadanut/legacy-cloud-acl:latest
    ports:
      - "8180:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/cloud-product-synchronizer
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=[PASS]
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_FLYWAY_URL=jdbc:postgresql://localhost:5432/cloud-product-synchronizer
      - SPRING_FLYWAY_SCHEMAS=public
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=[PASS]
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,prometheus,info
    networks: [ "microservices" ]
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [ "microservices" ]
    
  grafana:
    container_name: grafana_container
    restart: always
    build: monitoring/grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - '3000:3000'
    networks: [ "microservices" ]
    
networks:
  microservices:
    name: microservices